# Pays
type Country @table(key: "id") {
    id: ID!            # Identifiant unique du pays
    slug: String!      # Identifiant de l'URL pour le pays
    code: String       # Code du pays (ex: FR pour France)
}


# Ville
type City @table(key: "id") {
    id: ID!            # Identifiant unique de la ville
    country: Country!  # Référence au pays
    parentCity: City   # Référence à la ville parente si elle existe
    slug: String!      # Identifiant de l'URL pour la ville
    lat: Float!        # Latitude
    lng: Float!        # Longitude
    mainImg: String    # Image principale de la ville
    visible: Boolean   # Statut de visibilité
    timezone: String   # Fuseau horaire de la ville
}


# Type de lieu (ex: attraction touristique, restaurant, etc.)
enum PlaceType {
    TOURIST_ATTRACTION
    HOTEL
    RESTAURANT_BAR
    NICE_SURROUNDINGS
}

# Lieu (ex: restaurant, hôtel, attraction)
type Place @table(key: "id") {
    id: ID!             # Identifiant unique du lieu
    city: City!         # Référence à la ville
    area: Area          # Référence à la zone si applicable
    type: PlaceType     # Type de lieu
    slug: String        # Identifiant de l'URL pour le lieu
    lat: Float!         # Latitude
    lng: Float!         # Longitude
    address: String     # Adresse
    zipCode: String     # Code postal
    googleRating: Float # Note Google
}

